"""ICR_reasoning/prompts/templates.py — re-exports from prompts/templates.py."""
from prompts.templates import (  # noqa: F401
    ROADMAP_PROMPT,
    DECISION_TREE_PROMPT,
    CASE_STUDIES_PROMPT,
    SCORING_PROMPT,
    SCORING_PROMPT_COT_FIRST,
    DT_MAX_TOKENS,
    CS_MAX_TOKENS,
    SCORING_MAX_TOKENS,
    CASE_STUDY_WITH_REASONING_PROMPT,
    FLUSH_MAX_TOKENS,
)

__all__ = [
    "ROADMAP_PROMPT",
    "DECISION_TREE_PROMPT",
    "CASE_STUDIES_PROMPT",
    "SCORING_PROMPT",
    "SCORING_PROMPT_COT_FIRST",
    "DT_MAX_TOKENS",
    "CS_MAX_TOKENS",
    "SCORING_MAX_TOKENS",
    "CASE_STUDY_WITH_REASONING_PROMPT",
    "FLUSH_MAX_TOKENS",
]
