"""
generators/initial.py — Generate the initial Cheatsheet from labeled seed examples.

The initial cheatsheet has two parts:
  1. DECISION TREE  — generated by asking the LLM to write a step-by-step
                      procedure grounded in the seed examples.
  2. SEED CASE STUDIES — N case studies that identify structural patterns in
                         the seed examples and state actionable rules.

This runs once at the start of the pipeline. The decision tree is fixed after
this point; case studies continue to accumulate during training.

Standalone usage
----------------
    python -m ICR_naive.generators.initial \\
        --dataset path/to/dataset.jsonl \\
        --n-seed 30 --output-dir runs/init
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from dotenv import load_dotenv

from ..core.cheatsheet import CASE_STUDY_MAX_CHARS, Cheatsheet
from ..core.data import is_true, load_jsonl, sample_instances
from ..core.llm_client import call_llm, get_api_key
from ..core.parser import split_case_studies
from utils.case_study import CaseStudy
from ..prompts.templates import (
    CASE_STUDIES_PROMPT,
    DECISION_TREE_PROMPT,
    CS_MAX_TOKENS,
    DT_MAX_TOKENS,
)

load_dotenv(Path(__file__).parent.parent.parent / ".env")

DEFAULT_MODEL = "openai/gpt-4o"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _format_examples(instances: list[dict]) -> str:
    lines = []
    for i, it in enumerate(instances, 1):
        label = "TRUE" if is_true(it["answer"]) else "FALSE"
        lines.append(
            f"  {i:3d}. E1 = {it['equation1']}"
            f"  |  E2 = {it['equation2']}"
            f"  |  implies: {label}"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Core function
# ---------------------------------------------------------------------------

def generate_initial_cheatsheet(
    items: list[dict],
    model: str,
    api_key: str,
    n_seed_true: int = 15,
    n_seed_false: int = 15,
    n_studies: int = 3,
    seed: int = 42,
    temperature: float = 0.3,
) -> Cheatsheet:
    """
    Generate the initial Cheatsheet from labeled training examples.

    Steps:
      1. Sample n_seed_true TRUE + n_seed_false FALSE examples.
      2. Ask the LLM to produce a decision tree from those examples.
      3. Ask the LLM to produce n_studies seed case studies.
      4. Return a Cheatsheet with both.
    """
    instances = sample_instances(items, n_seed_true, n_seed_false, seed)
    example_lines = _format_examples(instances)

    # Step 1: decision tree
    print("  [init] Generating decision tree ...", file=sys.stderr)
    decision_tree = call_llm(
        DECISION_TREE_PROMPT.format(example_lines=example_lines),
        model, api_key,
        temperature=temperature,
        max_tokens=DT_MAX_TOKENS,
    )

    # Step 2: seed case studies
    print(f"  [init] Generating {n_studies} seed case studies ...", file=sys.stderr)
    cs_max_tokens = int(n_studies * CASE_STUDY_MAX_CHARS / 4 * 1.2)
    cs_text = call_llm(
        CASE_STUDIES_PROMPT.format(
            decision_tree=decision_tree,
            example_lines=example_lines,
            n_studies=n_studies,
        ),
        model, api_key,
        temperature=temperature,
        max_tokens=cs_max_tokens,
    )

    case_studies = [CaseStudy.from_text(s) for s in split_case_studies(cs_text)]
    if not case_studies:
        case_studies = [CaseStudy.from_text(cs_text.strip())]

    return Cheatsheet(decision_tree=decision_tree, case_studies=case_studies)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate the initial cheatsheet (decision tree + seed case studies).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--dataset",       required=True, metavar="FILE")
    p.add_argument("--n-seed-true",   type=int, default=15, metavar="N")
    p.add_argument("--n-seed-false",  type=int, default=15, metavar="N")
    p.add_argument("--n-studies",     type=int, default=3,  metavar="N")
    p.add_argument("--seed",          type=int, default=42, metavar="SEED")
    p.add_argument("--model",         default=DEFAULT_MODEL, metavar="MODEL_ID")
    p.add_argument("--temperature",   type=float, default=0.3, metavar="T")
    p.add_argument("--output-dir",    default="runs/init", metavar="DIR")
    return p


def main() -> None:
    args = _build_parser().parse_args()
    api_key = get_api_key()

    dataset_path = Path(args.dataset)
    if not dataset_path.exists():
        raise SystemExit(f"Error: dataset not found: {dataset_path}")

    items = load_jsonl(dataset_path)
    print(
        f"Loaded {len(items)} items. Generating initial cheatsheet with {args.model} ...",
        file=sys.stderr,
    )

    cs = generate_initial_cheatsheet(
        items=items,
        model=args.model,
        api_key=api_key,
        n_seed_true=args.n_seed_true,
        n_seed_false=args.n_seed_false,
        n_studies=args.n_studies,
        seed=args.seed,
        temperature=args.temperature,
    )

    out_dir = Path(args.output_dir)
    cs.save(out_dir / "cheatsheet")
    print(cs.render())
    print(f"\n[Saved to {out_dir}]", file=sys.stderr)
    print(cs.summary(), file=sys.stderr)


if __name__ == "__main__":
    main()
